name: assistindia
description: AssistIndia - SMS Sender (com.rupeedesk) - Flutter (Dark theme)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ Firebase
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0

  # âš™ï¸ Background + SMS
  workmanager:
  git:
    url: https://github.com/fluttercommunity/flutter_workmanager.git
    ref: main
  another_telephony: ^0.4.1

  # âš¡ Utilities
  permission_handler: ^11.4.0
  shared_preferences: ^2.3.2
  provider: ^6.1.5
  google_fonts: ^4.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true