name: assistindia
description: AssistIndia - SMS Sender (com.rupeedesk) - Flutter (Dark theme)
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  workmanager: ^0.5.2
  sms_advanced: ^1.1.2
flutter_sms_inbox: ^1.0.5
  permission_handler: ^11.1.0
  shared_preferences: ^2.3.2
  provider: ^6.0.5
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
